version: '3.8'

services:

  redis:
    image: redis:7.2.1-alpine
    container_name: "redis"
    restart: always
    ports:
      - "6379:6379"
    volumes: 
      - cache:/data

  app:
    build: .
    command: ["python3", "app.py"]
    volumes:
      - "./:/code"
    ports:
      - "5000:5000"
    depends_on:
        - redis

volumes:
  cache:
    driver: local

